/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mcassist;

import javax.swing.JLabel;

/**
 *
 * @author am728605
 */
public class Step extends javax.swing.JPanel {

    /**
     * Creates new form Step
     */
    public Step() { 
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        stepLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(276, 180));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mcassist/images/Crafting_GUI.png"))); // NOI18N
        add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        stepLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stepLabel.setText("Etape X");
        add(stepLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JLabel stepLabel;
    // End of variables declaration//GEN-END:variables

    void setStepNumber(int index) {
        stepLabel.setText("Etape " + index);
    }
}
